version: '3.8'

services:
  edgecom-nat:
    container_name: nat
    build:
      context: ./nat
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - nat.free5gc.org
      privnet_n6:
        aliases:
          - natn6.free5gc.org

  free5gc-upf:
    command: echo 'stop'

  free5gc-smf:
    depends_on:
      - edgecom-upf

  ueransim:
    image: free5gc/ueransim:v3.3.0
    depends_on:
      - edgecom-upf

  edgecom-upf:
    container_name: eupf
    image: ghcr.io/edgecomllc/eupf:0.4.0
    #image: eupf-local:latest
    privileged: true
    command: --iface eth0 --iface eth1 --n3addr 10.100.200.14 --nodeid 10.100.200.14 --paddr 10.100.200.14:8805 --attach generic
    volumes:
      - /sys/fs/bpf:/sys/fs/bpf
      - ./eupf/entrypoint.sh:/app/bin/entrypoint.sh
    environment:
      GIN_MODE: release
    ulimits:
      memlock: -1
    cap_add:
# Granular caps support depends on kernel version
#      - BPF
##      - TRACING
#      - PERFMON
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE # setrlimit
    ports:
      - "8080:8080"
      - "9090:9090"
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    networks:
      privnet_n6:
        aliases:
          - upfn6.free5gc.org
      privnet:
        ipv4_address: 10.100.200.14
        aliases:
          - upf.free5gc.org

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9091:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      privnet:

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    networks:
      privnet:

networks:
  privnet_n6:
    ipam:
      driver: default
      config:
        - subnet: 10.100.250.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc-n6


volumes:
  prom_data:
