info:
  version: 1.0.2
  description: NRF initial local configuration

configuration:
  MongoDBName: free5gc # database name in MongoDB
  MongoDBUrl: mongodb://db:27017 # a valid URL of the mongodb
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: nrf.free5gc.org # IP used to serve NFs or register to another NRF
    bindingIPv4: nrf.free5gc.org  # IP used to bind the service
    port: 8000 # port used to bind the service
    cert: # the local path of TLS key
      pem: cert/nrf.pem # NRF TLS Certificate
      key: cert/nrf.key # NRF TLS Private key
    rootcert: # the local path of root CA certs
      pem: cert/nrf.pem
      key: cert/nrf.key
    oauth: true
  DefaultPlmnId:
    mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
    mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
  serviceNameList: # the SBI services provided by this NRF, refer to TS 29.510
    - nnrf-nfm # Nnrf_NFManagement service
    - nnrf-disc # Nnrf_NFDiscovery service

  # Metrics configuration
  # If using the same bindingIPv4 as the sbi server, make sure that the ports are different
  metrics:
    enable: false # (Optional, default false)
    scheme: http # (Required) the protocol for metrics (http or https, default https)
    bindingIPv4: nrf.free5gc.org # (Required) IP used to bind the metrics endpoint (default 0.0.0.0)
    port: 9091 # (Optional, default 9091) port used to bind the service
    tls: # (Optional) the local path of TLS key (Could be the same as the sbi ones)
      pem: cert/nrf.pem # NRF TLS Certificate
      key: cert/nrf.key # NRF TLS Private key
    namespace: free5gc # (Optional, default free5gc)

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
