info:
  version: 1.0.0
  description: UPF configuration

configuration:
  # debugLevel: panic|fatal|error|warn|info|debug|trace
  debugLevel: info

  pfcp:
    - addr: upf2.free5gc.org

  gtpu:
    - addr: upf2.free5gc.org
    # [optional] gtpu.name
    # - name: upf.5gc.nctu.me
    # [optional] gtpu.ifname
    # - ifname: gtpif

  dnn_list:
    - dnn: internet
      cidr: 60.60.0.0/16
      # [optional] apn_list[*].natifname
      # natifname: eth0
    - dnn: internet2
      cidr: 10.10.0.0/16
      # [optional] apn_list[*].natifname
      # natifname: eth0
